server:
  port: 8088
spring:
  datasource:
    password: Legendary
    url: jdbc:mysql://localhost:3306/demo
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
     key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


